stages:
  - test
  - build
  - docker

variables:
  IMAGE_NAME: "$DOCKERHUB_USERNAME/test-app"

test-runner:
  stage: test
  script:
    - echo "Hello from GitLab Runner"
    - echo "Runner is working"

build-react:
  stage: build
  image: node:22
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week

docker:
  stage: docker

  image: docker:27

  services:
    - docker:27-dind

  script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker build -t "$IMAGE_NAME:latest" .
    - docker push "$IMAGE_NAME:latest"